name: Auto merge Jule PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    if: github.actor == 'WenYuHo'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable auto merge and delete branch
        run: gh pr merge ${{ github.event.pull_request.number }} --auto --squash --delete-branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
